### ISSUE TITLE
VMware Fusion & Vagrant on mac M1

### ISSUE THREAD

**Issue by ostryweb-cz** [sloopstash/kickstart-linux#22]
Hi, I followed the instructions in your article ( https://sloopstash.com/blog/how-to-build-vm-on-apple-m1-m2-chip-mac-with-vmware-fusion-and-vagrant.html ), however I still end up with this error:

```
Bringing machine 'sloopstash-ubuntu-linux-22-04-server' up with 'vmware_fusion' provider...
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
```

**Comment by sujankumar45** [comment]
Hi [ostryweb-cz](https://github.com/ostryweb-cz) can you try with below updated command 

`$ sudo VAGRANT_CWD=./vagrant/ubuntu-linux-22-04/vmware/arm64/server vagrant up`

**Comment by ostryweb-cz** [comment]
> Hi [ostryweb-cz](https://github.com/ostryweb-cz) can you try with below updated command
> 
> `$ sudo VAGRANT_CWD=./vagrant/ubuntu-linux-22-04/vmware/arm64/server vagrant up`

Hi, this produces same error, In fact this is the same command as is in the article..
Anyway I tried to re-install everything and get the same result..

**Comment by JohnSundarraj** [comment]
Hi @ostryweb-cz , we recently tested with following versions and it worked as expected.

```
VMware Fusion Player: 13.5.0
Vagrant: 2.4.1
Vagrant plugin: vagrant-vmware-desktop=3.0.3 
```

Please try with these versions and let us know the result. Thank you.
