### ISSUE TITLE
Unable to install Linux in the vagrant file

### ISSUE THREAD

**Issue by Elvinfernandez** [sloopstash/kickstart-linux#24]
I was trying to install docker and I was trying to do it from the prerequisites from the Linux and I’m stuck at this point

 /opt/kickstart-linux (master)
$ VAGRANT_CWD=./vagrant/ubuntu-linux-18-04/virtualbox/amd64/server vagrant up
Bringing machine 'sloopstash-ubuntu-linux-18-04-server' up with 'virtualbox' provider...
==> sloopstash-ubuntu-linux-18-04-server: Box 'sloopstash/ubuntu-linux-18-04' could not be found. Attempting to find and install...
    sloopstash-ubuntu-linux-18-04-server: Box Provider: virtualbox
    sloopstash-ubuntu-linux-18-04-server: Box Version: 1.1.1
The box 'sloopstash/ubuntu-linux-18-04' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
vagrant login. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/sloopstash/ubuntu-linux-18-04"]
Error: SSL certificate problem: unable to get local issuer certificate

**Comment by Elvinfernandez** [comment]
Hi Team
Thank you for the update, I have delete vmbox, vagrant, git and I have followed the link https://github.com/sloopstash/kickstart-linux/wiki , and have installed the whole application, still I am getting the same error, request to please help on this.

**Comment by DivyaPriya-Muthuvel** [comment]
Hi Elvin,

As next step, we request you can upgrade to  [**Vagrant 2.3.7**](https://releases.hashicorp.com/vagrant/2.3.7/vagrant_2.3.7_windows_amd64.msi) and try to turn up your VM.
