### ISSUE TITLE
Getting error message while trying to up the ubuntu-linux-22-04 VM

### ISSUE THREAD

**Issue by ragunaathbabu** [sloopstash/kickstart-linux#25]
Hi Team,

I got the below error message while trying to up the ubuntu-linux-22-04.
VAGRANT_CWD=./vagrant/ubuntu-linux-22-04/virtualbox/amd64/server Vagrant up

sloopstash-ubuntu-linux-22-04-server: SSH auth method: private key
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
    sloopstash-ubuntu-linux-22-04-server: Warning: Authentication failure. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Also I checked there is config.vm.boot_timeout value configured.**

And **VAGRANT_CWD=./vagrant/ubuntu-linux-22-04/virtualbox/amd64/server Vagrant ssh**  is working and login into VM.

Is there any reason for this **Warning: Authentication failure. Retrying...** error message.

**Comment by JohnSundarraj** [comment]
@ragunaathbabu, it is an SSH auth failure warning due to intense CPU pressure. I recommend you to raise the `vb.cpus` count to `2` and try. Then the warning should not be raised. Anyhow, this is just a warning, as long as you can SSH to the VM, it's totally fine. Thank you.
