### ISSUE TITLE
Vagrant SSH timeout issue: unable to boot Ubuntu 18.04 server VM on Windows 11 with VirtualBox

### ISSUE THREAD

**Issue by DivyaPriya-Muthuvel** [sloopstash/kickstart-linux#27]
I followed the steps mentioned in Kickstart-Linux wiki home page and installed the Vagrant and Virtualbox as mentioned in the document. I'm trying to boot the ubuntu-linux-18-04 server. I'm facing an error.

Vagrant version : **2.2.9**
Virtualbox version : **6.1.36**
OS : **Windows 11**
Processor : **i5**
Memory : **8GB**

```
Divya@DESKTOP-5QK0EFI MINGW64 /opt/kickstart-linux (master)
$ VAGRANT_CWD=./vagrant/ubuntu-linux-18-04/virtualbox/amd64/server vagrant up
Bringing machine 'sloopstash-ubuntu-linux-18-04-server' up with 'virtualbox' provider...
==> sloopstash-ubuntu-linux-18-04-server: Clearing any previously set forwarded ports...
==> sloopstash-ubuntu-linux-18-04-server: Fixed port collision for 22 => 2222. Now on port 2200.
==> sloopstash-ubuntu-linux-18-04-server: Clearing any previously set network interfaces...
==> sloopstash-ubuntu-linux-18-04-server: Preparing network interfaces based on configuration...
    sloopstash-ubuntu-linux-18-04-server: Adapter 1: nat
    sloopstash-ubuntu-linux-18-04-server: Adapter 2: hostonly
==> sloopstash-ubuntu-linux-18-04-server: Forwarding ports...
    sloopstash-ubuntu-linux-18-04-server: 22 (guest) => 2200 (host) (adapter 1)
==> sloopstash-ubuntu-linux-18-04-server: Running 'pre-boot' VM customizations...
==> sloopstash-ubuntu-linux-18-04-server: Booting VM...
==> sloopstash-ubuntu-linux-18-04-server: Waiting for machine to boot. This may take a few minutes...
    sloopstash-ubuntu-linux-18-04-server: SSH address: 127.0.0.1:2200
    sloopstash-ubuntu-linux-18-04-server: SSH username: vagrant
    sloopstash-ubuntu-linux-18-04-server: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.
 
If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.
 
If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.
 
If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

```

**Comment by sujankumar45** [comment]
Thank you for reaching out about the issue you're facing with booting the Ubuntu 18.04 server VM on Windows 11 with VirtualBox. Based on the information you've provided, it seems like there might be a couple of things we can try to troubleshoot and resolve the problem.

Firstly, if you're running any antivirus software on your system, please try temporarily disabling it and then attempt to boot the VM again. Sometimes, antivirus software can interfere with the virtualization process and cause issues like the one you're experiencing.

Additionally, let's try adjusting the number of CPUs allocated to the VM. You can do this by editing the Vagrantfile located at **vagrant/ubuntu-linux-18-04/virtualbox/amd64/server/Vagrantfile.** Find the line that specifies vb.cpus = "1" and change it to **vb.cpus = "2"**. This should allocate more CPU resources to the VM and might help with the booting process.

After making these changes, try booting the VM again and see if the issue persists. If you encounter any further problems or have any questions, please feel free to reach out.
