### ISSUE TITLE
SSH authentication failure warning for Alma Linux 9.

### ISSUE THREAD

**Issue by srirameaswar** [sloopstash/kickstart-linux#28]
```
export OS_NAME=alma-linux-9
export OS_ARCHITECTURE=amd64
export OS_EDITION=server
export HYPERVISOR=virtualbox
```

Then I started the command VAGRANT_CWD=./vagrant/$OS_NAME/$HYPERVISOR/$OS_ARCHITECTURE/$OS_EDITION vagrant up from the kickstart-linux directory.

The installation or boot is interrupted by the warning :  SSH authentication failure warning for Alma Linux 9.

**Comment by JohnSundarraj** [comment]
@srirameaswar I believed the issue is fixed. Hence closing the thread.
